eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/npawlenko/cloud-config

server:
  port: 8888
