spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud_user
    username: postgresql
    password: postgresql
  jpa:
    show-sql: true
  application:
    name: user-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
