spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud
    username: postgresql
    password: postgresql
  jpa:
    show-sql: true
  application:
    name: payment-service
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
