spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud_payment
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: payment-service
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/